export const SPECIALTIES = [
  { value: 101, label: 'ANATOMIA PATOLOGICA' },
  { value: 103, label: 'CARDIOLOGIA' },
  { value: 104, label: 'CIRUGIA CARDIOVASCULAR' },
  { value: 105, label: 'CIRUGIA DE CABEZA Y CUELLO' },
  { value: 106, label: 'CIRUGIA GENERAL' },
  { value: 107, label: 'CIRUGIA PEDIATRICA' },
  { value: 108, label: 'CIRUGIA PLASTICA, ESTETICA Y REPARADORA' },
  { value: 109, label: 'CRECIMIENTO Y DESARROLLO' },
  { value: 110, label: 'DENSITOMETRIA OSEA' },
  { value: 111, label: 'DERMATOLOGIA' },
  { value: 112, label: 'ECOGRAFIA' },
  { value: 113, label: 'ENDOCRINOLOGIA' },
  { value: 114, label: 'ESTRATEGIAS SANITARIAS' },
  { value: 115, label: 'GASTROENTEROLOGIA' },
  { value: 116, label: 'GERIATRIA' },
  { value: 117, label: 'GINECOLOGIA' },
  { value: 118, label: 'HEMATOLOGIA' },
  { value: 119, label: 'LABORATORIO CLINICO' },
  { value: 120, label: 'MAMOGRAFIA' },
  { value: 121, label: 'MEDICINA FISICA Y REHABILITACION' },
  { value: 122, label: 'MEDICINA GENERAL' },
  { value: 123, label: 'MEDICINA INTERNA' },
  { value: 124, label: 'MEDICINA NUCLEAR' },
  { value: 125, label: 'NEFROLOGIA' },
  { value: 126, label: 'NEUMOLOGIA' },
  { value: 127, label: 'NEUROCIRUGIA' },
  { value: 128, label: 'NEUROLOGIA' },
  { value: 129, label: 'NUTRICION' },
  { value: 130, label: 'OBSTETRICIA' },
  { value: 131, label: 'ODONTOLOGIA' },
  { value: 132, label: 'OFTALMOLOGIA' },
  { value: 133, label: 'ONCOLOGIA' },
  { value: 134, label: 'OTORRINOLARINGOLOGIA' },
  { value: 135, label: 'PEDIATRIA' },
  { value: 136, label: 'PODOLOGIA GENERAL' },
  { value: 137, label: 'PSICOLOGIA' },
  { value: 138, label: 'PSIQUIATRIA' },
  { value: 139, label: 'RADIOLOGIA' },
  { value: 140, label: 'RESONANCIA MAGNETICA' },
  { value: 141, label: 'REUMATOLOGIA' },
  { value: 142, label: 'TOMOGRAFIA ESPIRAL MULTICORTE' },
  { value: 143, label: 'TOPICO' },
  { value: 144, label: 'TRAUMATOLOGIA' },
  { value: 145, label: 'URGENCIAS Y EMERGENCIAS MEDICAS' },
  { value: 146, label: 'UROLOGIA' },
  { value: 148, label: 'CENTRO QUIRURGICO' },
  { value: 150, label: 'INMUNOLOGIA' },
  { value: 151, label: 'MASTOLOGIA' },
  { value: 152, label: 'TRASLADO EN AMBULANCIA' },
  { value: 153, label: 'UNIDAD DE TRATAMIENTO DEL DOLOR' },
  { value: 154, label: 'UNIDAD DE TRATAMIENTO LASER' },
  { value: 155, label: 'UNIDAD DE TRATAMIENTO DE LA INFERTILIDAD' },
  { value: 156, label: 'ADMINISTRACION HOSPITALARIA' },
  { value: 157, label: 'CIRUGIA DE CABEZA Y CUELLO-SOP' },
  { value: 158, label: 'CIRUGIA GENERAL-SOP' },
  { value: 159, label: 'CIRUGIA ONCOLOGICA' },
  { value: 160, label: 'CIRUGIA ONCOLOGICA-SOP' },
  { value: 161, label: 'CIRUGIA PEDIATRICA-SOP' },
  { value: 162, label: 'CIRUGIA PLASTICA, ESTETICA Y REPARADORA-SOP' },
  { value: 163, label: 'GINECOLOGIA-SOP' },
  { value: 164, label: 'OFTALMOLOGIA-SOP' },
  { value: 165, label: 'OTORRINOLARINGOLOGIA-SOP' },
  { value: 166, label: 'TRAUMATOLOGIA-SOP' },
  { value: 167, label: 'UROLOGIA-SOP' },
  { value: 168, label: 'MEDICINA HIPERBARICA' },
  { value: 171, label: 'MEDICINA DEL NIÑO' },
  { value: 172, label: 'MEDICINA COMPLEMENTARIA' },
  { value: 173, label: 'OZONOTERAPIA' },
  { value: 174, label: 'SCANNER PODOLOGICO' },
  { value: 175, label: 'MASOTERAPIA' },
  { value: 176, label: 'MEDICINA ALTERNATIVA' },
  { value: 177, label: 'MEDICINA ESTETICA' },
  { value: 178, label: 'MEDICINA FAMILIAR Y COMUNITARIA' },
  { value: 179, label: 'DERMATOLOGIA LASER' },
  { value: 180, label: 'INFECTOLOGIA' },
  { value: 181, label: 'ONCOLOGIA INTEGRATIVA' },
  { value: 182, label: 'SOPORTE METABOLICO NUTRICIONAL' },
  { value: 184, label: 'MEDICINA ONCOLOGICA' },
  { value: 185, label: 'ANESTESIOLOGIA' },
  { value: 190, label: 'DERMATOLOGIA ESTETICA' },
  { value: 191, label: 'FLEBOLOGIA' },
  { value: 200, label: 'AMBULANCIA EVENTOS' },
  { value: 201, label: 'ANGIOLOGIA' },
  { value: 202, label: 'CIRUGIA VASCULAR' },
  { value: 203, label: 'CENTRO QUIRURGICO' },
  { value: 204, label: 'HOSPITALIZACION' },
  { value: 205, label: 'EMERGENCIA' },
  { value: 206, label: 'CONSULTA EXTERNA' },
  { value: 207, label: 'IMAGENES' },
  { value: 208, label: 'PROCEDIMIENTO' },
  { value: 209, label: 'SIN ESPECIALIDAD' },
  { value: 210, label: 'INTERCONSULTA HOSPITALIZACION Y EMERGENCIA' },
  { value: 211, label: 'FARMACIA O BOTICA' },
  { value: 212, label: 'FARMACIA ESPECIALIZADA DERMATOLOGICA' },
  { value: 213, label: 'FARMACIA OFTALMOLOGICA' },
  { value: 214, label: 'OPTICA' },
  { value: 215, label: 'SERVICIOS HIGIENICOS' },
  { value: 216, label: 'VENTA DE PRODUCTOS DERMATOLOGICOS' },
  { value: 217, label: 'CAMARA HIPERBARICA' },
  { value: 218, label: 'SALUD OCUPACIONAL' },
  { value: 219, label: 'ENFERMEDADES INFECCIOSAS Y TROPICALES' },
  { value: 220, label: 'VACUNACIÓN E INMUNIZACIÓN' },
  { value: 221, label: 'SERVICIOS MEDICOS DE SALUD' },
  { value: 222, label: 'VENTA DE APARATOS AUDITIVOS' },
  { value: 223, label: 'FARMACIA' },
  { value: 224, label: 'TOMOGRAFIA DENTAL' },
  { value: 225, label: 'VENTA DE PRODUCTOS ORTOPEDICOS' },
  { value: 226, label: 'ECOGRAFIA REUMATOLOGICA' },
  { value: 227, label: 'NEUROFISIOLOGIA' },
  { value: 228, label: 'CIRUGIA PLASTICA' },
  { value: 229, label: 'SALA DE OPERACIONES' },
  { value: 230, label: 'TERAPIA FISICA Y REHABILITACION' },
  { value: 231, label: 'CIRUGIA REFRACTIVA' },
  { value: 232, label: 'TERAPIA EN SILLA' },
  { value: 233, label: 'ECOGRAFIA UROLOGICA' },
  {
    value: 234,
    label: 'ABLACIÓN TUMORAL Y OTROS POR HIFU (ULTRASONIDO FOCALIZADO DE ALTA INTENSIDAD)',
  },
  { value: 235, label: 'CAMPAÑA - NEUMOLOGIA' },
  { value: 236, label: 'CAMPAÑA - DERMATOLOGIA' },
  { value: 237, label: 'CAMPAÑA - GASTROENTEROLOGIA' },
  { value: 238, label: 'CAMPAÑA - UROLOGIA' },
  { value: 239, label: 'CAMPAÑA - REUMATOLOGIA' },
];

export function specialityToLabel(value: number): string {
  return SPECIALTIES.find((_) => _.value === value)?.label ?? '';
}

export const searchSpecialties = (value: string) => {
  if (!value || value.trim() === '') {
    return SPECIALTIES;
  }

  const search = value.trim().toLowerCase();

  return SPECIALTIES.filter((specialty) => specialty.label.toLowerCase().includes(search));
};
